Type = Primitive | Complex;


Primitive = Int | String | Bool;

Int = INT, PIPE, [NumberRange];
String = STRING, PIPE, [NumberRange];
Bool = BOOL, PIPE, [TRUE | FALSE];


Complex = Array | LiteralArray | Map | LiteralMap;

Array = ARRAY, SEMICOLON, NumberRange, SEMICOLON, CompoundType, {SEMICOLON, NumberRange, COLON, CompoundType};

LiteralArray = LSQUARE, CompoundType, {COMMA, CompoundType}, RSQUARE;

Map = MAP, SEMICOLON, NumberRange, SEMICOLON, CompoundType, SEMICOLON, CompoundType, {SEMICOLON, StringLiteral, COLON, CompoundType};

LiteralMap = LBRACE, StringLiteral, COLON, CompoundType, {COMMA, StringLiteral, COLON, CompoundType}, RBRACE;


InQuoteType = QUOTE, Type, QUOTE;
CompoundType = InQuoteType | (LPAREN, InQuoteType, {COLON, InQuoteType}, RPAREN);
NumberRange = Number | (LPAREN, [Number], UNDERSCORE, [Number], RPAREN);
